name: ""
description: ""

url: "https://esytastic.github.io"

paginate: 10

destination: ./app
source: ./jekyll
markdown: rdiscount
permalink: pretty
highlighter: pygments
keep_files: [images, styles, scripts, bower_components, views]
